{
 "title": "JMeter Comparison Dashboard",
 "description": "Compare 2 load tests",
 "tags": [ "load_test" ],
 "time": { "from": "2020-12-04T15:08:37.900Z", "to": "2020-12-04T15:17:23.584Z" },
 "templating": {
  "list": [
   { "name": "jmeter_data_source", "query": "influxdb" },
   {
    "name": "jmeter_application",
    "query": "SHOW TAG VALUES FROM \"jmeter\" WITH KEY = \"application\""
   },
   {
    "name": "jmeter_testId",
    "query": "SHOW TAG VALUES FROM \"jmeter\" WITH KEY = \"testId\""
   },
   { "name": "jmeter_transactions_filter", "query": "Login.*" },
   {
    "name": "jmeter_transaction_details",
    "query": "SHOW TAG VALUES FROM \"jmeter\" WITH KEY = \"transaction\" WHERE \"application\" =~ /^$jmeter_application$/ AND \"testId\" =~ /^$jmeter_testId$/ AND \"transaction\" != 'internal' AND \"transaction\" != 'all'"
   },
   { "name": "jmeter_measurement_name", "label": "JMeter Measurement name", "query": "jmeter" },
   {
    "name": "send_interval",
    "label": "Backend send interval in second",
    "query": "5"
   },
   { "name": "server_data_source", "query": "prometheus" },
   {
    "name": "server_cluster",
    "query": "label_values(kube_pod_info, cluster)"
   },
   {
    "name": "server_namespace",
    "query": "label_values(kube_pod_info{cluster=\"$server_cluster\"}, namespace)"
   },
   {
    "name": "server_workload_type",
    "query": "label_values(mixin_pod_workload{namespace=~\"$server_namespace\", workload=~\".+\"}, workload_type)"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Requests",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"count\")  FROM \"$jmeter_measurement_name\" WHERE (\"application\" =~ /^$jmeter_application$/ AND \"testId\" =~ /^$jmeter_testId$/ AND \"transaction\" = 'all') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failed Requests",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"countError\") FROM \"$jmeter_measurement_name\" WHERE (\"transaction\" = 'all' AND \"application\" =~ /^$jmeter_application$/ AND \"testId\" =~ /^$jmeter_testId$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Received Bytes",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "format": "bytes",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"rb\") FROM \"$jmeter_measurement_name\" WHERE (\"transaction\" = 'all' AND \"application\" =~ /^$jmeter_application$/ AND \"testId\" =~ /^$jmeter_testId$/) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sent Bytes",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "format": "bytes",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"sb\") FROM \"$jmeter_measurement_name\" WHERE (\"transaction\" = 'all' AND \"application\" =~ /^$jmeter_application$/ AND \"testId\" =~ /^$jmeter_testId$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Error Rate %",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "format": "percentunit",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"error\") / sum(\"all\") FROM (SELECT sum(\"count\") AS \"all\" FROM \"$jmeter_measurement_name\" WHERE \"transaction\" = 'all' AND \"application\" =~ /^$jmeter_application$/ AND \"testId\" =~ /^$jmeter_testId$/ AND $timeFilter GROUP BY time($__interval) fill(null)), (SELECT sum(\"countError\") AS \"error\" FROM \"$jmeter_measurement_name\" WHERE \"transaction\" = 'all' AND \"application\" =~ /^$jmeter_application$/ AND \"testId\" =~ /^$jmeter_testId$/ AND $timeFilter GROUP BY time($__interval) fill(null))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Req / s - $tag_testId",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "jmeter",
     "query": "SELECT mean(\"count\") / $send_interval FROM \"$jmeter_measurement_name\" WHERE (\"transaction\" = 'all' AND \"application\" =~ /^$jmeter_application$/ AND \"testId\" =~ /^$jmeter_testId$/) AND $timeFilter GROUP BY time($__interval), testId fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$jmeter_application$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Num of Errors - $tag_testId",
     "groupBy": [
      { "params": [ "$aggregation" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"countError\") FROM \"$jmeter_measurement_name\" WHERE (\"transaction\" = 'all' AND \"application\" =~ /^$jmeter_application$/ AND \"testId\" =~ /^$jmeter_testId$/) AND $timeFilter GROUP BY time($__interval),testId fill(null)",
     "select": [
      [
       { "params": [ "countError" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$jmeter_application$/" }
     ]
    }
   ]
  },
  {
   "title": "Active Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Threads - $tag_testId",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"maxAT\") FROM \"$jmeter_measurement_name\" WHERE (\"transaction\" = 'internal' AND \"application\" =~ /^$jmeter_application$/ AND \"testId\" =~ /^$jmeter_testId$/) AND $timeFilter GROUP BY time($__interval), testId fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Transactions Response Times (95th pct)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_transaction - $tag_testId",
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "measurement": "jmeter",
     "query": "SELECT \"pct95.0\" FROM \"jmeter\" WHERE (\"statut\" = 'ok' AND \"application\" =~ /^$jmeter_application$/ AND \"testId\" =~ /^$jmeter_testId$/ AND \"transaction\" =~ /^$jmeter_transactions_filter$/) AND $timeFilter GROUP BY \"transaction\",\"testId\"",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "statut", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$jmeter_application$/" },
      { "condition": "AND", "key": "testId", "operator": "=~", "value": "/^$jmeter_testId$/" }
     ]
    },
    {
     "alias": "Threads",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"maxAT\") FROM \"$jmeter_measurement_name\" WHERE (\"transaction\" = 'internal' AND \"application\" =~ /^$jmeter_application$/ AND \"testId\" =~ /^$jmeter_testId$/ AND \"transaction\" =~ /^$jmeter_transactions_filter$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}