{
 "title": "JMeter+Openshift Dashboard",
 "description": "Monitor your Apache JMeter load test and server-side Openshift performance in real time",
 "tags": [
  "load_test",
  "openshift"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "jmeter_data_source", "query": "influxdb" },
   {
    "name": "jmeter_application",
    "query": "SHOW TAG VALUES FROM \"jmeter\" WITH KEY = \"application\""
   },
   {
    "name": "jmeter_transaction_details",
    "query": "SHOW TAG VALUES FROM \"jmeter\" WITH KEY = \"transaction\" WHERE \"application\" =~ /^$jmeter_application$/ AND \"transaction\" != 'internal' AND \"transaction\" != 'all'"
   },
   { "name": "jmeter_measurement_name", "label": "JMeter Measurement name", "query": "jmeter" },
   {
    "name": "send_interval",
    "label": "Backend send interval in second",
    "query": "5"
   },
   { "name": "server_data_source", "query": "prometheus" },
   {
    "name": "server_cluster",
    "query": "label_values(kube_pod_info, cluster)"
   },
   {
    "name": "server_namespace",
    "query": "label_values(kube_pod_info{cluster=\"$server_cluster\"}, namespace)"
   },
   {
    "name": "server_workload_type",
    "query": "label_values(mixin_pod_workload{namespace=~\"$server_namespace\", workload=~\".+\"}, workload_type)"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Requests",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"count\")  FROM \"$jmeter_measurement_name\" WHERE (\"application\" =~ /^$jmeter_application$/ AND \"transaction\" = 'all') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failed Requests",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"countError\") FROM \"$jmeter_measurement_name\" WHERE (\"transaction\" = 'all' AND \"application\" =~ /^$jmeter_application$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Received Bytes",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "format": "bytes",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"rb\") FROM \"$jmeter_measurement_name\" WHERE (\"transaction\" = 'all' AND \"application\" =~ /^$jmeter_application$/) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sent Bytes",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "format": "bytes",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"sb\") FROM \"$jmeter_measurement_name\" WHERE (\"transaction\" = 'all' AND \"application\" =~ /^$jmeter_application$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Error Rate %",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "format": "percentunit",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"error\") / sum(\"all\") FROM (SELECT sum(\"count\") AS \"all\" FROM \"$jmeter_measurement_name\" WHERE \"transaction\" = 'all' AND \"application\" =~ /^$jmeter_application$/ AND $timeFilter GROUP BY time($__interval) fill(null)), (SELECT sum(\"countError\") AS \"error\" FROM \"$jmeter_measurement_name\" WHERE \"transaction\" = 'all' AND \"application\" =~ /^$jmeter_application$/ AND $timeFilter GROUP BY time($__interval) fill(null))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Req / s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "jmeter",
     "query": "SELECT mean(\"count\") / $send_interval FROM \"$jmeter_measurement_name\" WHERE (\"transaction\" = 'all' AND \"application\" =~ /^$jmeter_application$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$jmeter_application$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Num of Errors",
     "groupBy": [
      { "params": [ "$aggregation" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"countError\") FROM \"$jmeter_measurement_name\" WHERE (\"transaction\" = 'all' AND \"application\" =~ /^$jmeter_application$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "countError" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$jmeter_application$/" }
     ]
    }
   ]
  },
  {
   "title": "Active Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Threads",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"maxAT\") FROM \"$jmeter_measurement_name\" WHERE (\"transaction\" = 'internal' AND \"application\" =~ /^$jmeter_application$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Transactions Response Times (95th pct)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_transaction",
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "measurement": "jmeter",
     "query": "SELECT mean(\"pct95.0\") FROM \"$jmeter_measurement_name\" WHERE (\"application\" =~ /^$jmeter_application$/) AND (\"transaction\" =~ /^[A-Z].*/) AND $timeFilter GROUP BY \"transaction\", time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "statut", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$jmeter_application$/" }
     ]
    },
    {
     "alias": "Threads",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"maxAT\") FROM \"$jmeter_measurement_name\" WHERE (\"transaction\" = 'internal' AND \"application\" =~ /^$jmeter_application$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Traffic",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"sb\") FROM \"$jmeter_measurement_name\" WHERE (\"application\" =~ /^$jmeter_application$/) AND $timeFilter GROUP BY \"transaction\", time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "sb" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"rb\") FROM \"$jmeter_measurement_name\" WHERE (\"application\" =~ /^$jmeter_application$/) AND $timeFilter GROUP BY \"transaction\", time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Openshift4 Server Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server Workload CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster=\"$server_cluster\", namespace=\"$server_namespace\"}* on(namespace,pod)  group_left(workload, workload_type) mixin_pod_workload{cluster=\"$server_cluster\", namespace=\"$server_namespace\", workload_type=\"$server_workload_type\"}) by (workload, workload_type)",
       "legendFormat": "{{workload}} - {{workload_type}}"
      }
     ]
    },
    {
     "title": "Server Workload Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{cluster=\"$server_cluster\", namespace=\"$server_namespace\", container!=\"\"}* on(namespace,pod)   group_left(workload, workload_type) mixin_pod_workload{cluster=\"$server_cluster\", namespace=\"$server_namespace\", workload_type=\"$server_workload_type\"}) by (workload, workload_type)",
       "legendFormat": "{{workload}} - {{workload_type}}"
      }
     ]
    }
   ]
  },
  { "title": "Openshift3 Server Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Server Pods CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$server_namespace\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Server Pods Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$server_namespace\", container_name!=\"\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Errors per Transaction",
     "type": "table-old",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 47 },
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\") FROM \"$jmeter_measurement_name\" WHERE (\"application\" =~ /^$jmeter_application$/ AND \"statut\" = 'ko') AND $timeFilter GROUP BY \"transaction\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$jmeter_application$/" },
        { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
       ]
      }
     ]
    },
    {
     "title": "Error Info",
     "type": "table-old",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 47 },
     "targets": [
      {
       "alias": "$tag_responseCode",
       "groupBy": [
        { "params": [ "responseCode" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\") FROM \"$jmeter_measurement_name\" WHERE (\"application\" =~ /^$jmeter_application$/ AND \"responseCode\" !~ /^$/) AND $timeFilter GROUP BY \"responseCode\",\"responseMessage\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" }
        ],
        [
         { "params": [ "responseMessage" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$jmeter_application$/" },
        { "condition": "AND", "key": "responseCode", "operator": "!~", "value": "/^$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Individual Transaction - $jmeter_transaction_details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Requests - $jmeter_transaction_details",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 48 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\") FROM \"$jmeter_measurement_name\" WHERE (\"application\" =~ /^$jmeter_application$/ AND \"transaction\" =~ /^$jmeter_transaction_details$/ AND \"statut\" = 'all') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        {
         "key": "transaction",
         "operator": "=~",
         "value": "/^$jmeter_transaction_details$/"
        },
        { "condition": "AND", "key": "statut", "operator": "=", "value": "all" }
       ]
      }
     ]
    },
    {
     "title": "Failed Requests - $jmeter_transaction_details",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 48 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\") FROM \"$jmeter_measurement_name\" WHERE (\"application\" =~ /^$jmeter_application$/ AND \"transaction\" =~ /^$jmeter_transaction_details$/ AND \"statut\" = 'ko') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        {
         "key": "transaction",
         "operator": "=~",
         "value": "/^$jmeter_transaction_details$/"
        },
        { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
       ]
      }
     ]
    },
    {
     "title": "Error Rate % - $jmeter_transaction_details",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 48 },
     "format": "percentunit",
     "valueName": "total",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"error\") / sum(\"all\") FROM (SELECT sum(\"count\") AS \"all\" FROM \"$jmeter_measurement_name\" WHERE \"transaction\" =~ /^$jmeter_transaction_details$/ AND \"statut\" = 'all' AND \"application\" =~ /^$jmeter_application$/ AND $timeFilter GROUP BY time($__interval) fill(null)), (SELECT sum(\"count\") AS \"error\" FROM \"$jmeter_measurement_name\" WHERE \"transaction\" =~ /^$jmeter_transaction_details$/ AND \"statut\" = 'ko' AND \"application\" =~ /^$jmeter_application$/ AND $timeFilter GROUP BY time($__interval) fill(null))",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        {
         "key": "transaction",
         "operator": "=~",
         "value": "/^$jmeter_transaction_details$/"
        },
        { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
       ]
      }
     ]
    },
    {
     "title": "Throughput - $jmeter_transaction_details",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Req / s",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "jmeter",
       "query": "SELECT last(\"count\") / $send_interval FROM \"$jmeter_measurement_name\" WHERE (\"transaction\" =~ /^$jmeter_transaction_details$/ AND \"statut\" = 'ok') AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "5s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        {
         "key": "transaction",
         "operator": "=~",
         "value": "/^$jmeter_transaction_details$/"
        },
        { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
       ]
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Num of Errors",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"count\") FROM \"$jmeter_measurement_name\" WHERE \"application\" =~ /^$jmeter_application$/ AND \"transaction\" =~ /^$jmeter_transaction_details$/ AND \"statut\" = 'ko' AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Response Times - $jmeter_transaction_details",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "Average",
       "groupBy": [
        { "params": [ "$aggregation" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT last(\"avg\") FROM \"$jmeter_measurement_name\" WHERE (\"transaction\" =~ /^$jmeter_transaction_details$/ AND \"statut\" = 'ok') AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "avg" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=~", "value": "/^$request$/" },
        { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
       ]
      },
      {
       "alias": "Median",
       "groupBy": [
        { "params": [ "$aggregation" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT last(\"pct50.0\") FROM \"$jmeter_measurement_name\" WHERE (\"transaction\" =~ /^$jmeter_transaction_details$/ AND \"statut\" = 'ok') AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "pct50.0" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=~", "value": "/^$request$/" },
        { "condition": "AND", "key": "statut", "operator": "=", "value": "all" }
       ]
      },
      {
       "alias": "90th Percentile",
       "groupBy": [
        { "params": [ "$aggregation" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT last(\"pct90.0\") FROM \"$jmeter_measurement_name\" WHERE (\"transaction\" =~ /^$jmeter_transaction_details$/ AND \"statut\" = 'ok') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "pct90.0" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=~", "value": "/^$request$/" },
        { "condition": "AND", "key": "statut", "operator": "=", "value": "all" }
       ]
      },
      {
       "alias": "95th Percentile",
       "groupBy": [
        { "params": [ "$aggregation" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT last(\"pct95.0\") FROM \"$jmeter_measurement_name\" WHERE (\"transaction\" =~ /^$jmeter_transaction_details$/ AND \"statut\" = 'ok') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "pct95.0" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=~", "value": "/^$request$/" }
       ]
      },
      {
       "alias": "99th Percentile",
       "groupBy": [
        { "params": [ "$aggregation" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT last(\"pct99.0\") FROM \"$jmeter_measurement_name\" WHERE (\"transaction\" =~ /^$jmeter_transaction_details$/ AND \"statut\" = 'ok') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "pct99.0" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=~", "value": "/^$request$/" }
       ]
      },
      {
       "alias": "Max",
       "groupBy": [
        { "params": [ "$aggregation" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT last(\"max\") FROM \"$jmeter_measurement_name\" WHERE (\"transaction\" =~ /^$jmeter_transaction_details$/ AND \"statut\" = 'ok') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "max" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=~", "value": "/^$request$/" },
        { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
       ]
      }
     ]
    }
   ]
  }
 ]
}