kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-data
  labels:
    app: grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ${K8S_STORAGE_CLASS}