kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: influxdb-data
  labels:
    app: influxdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ${K8S_STORAGE_CLASS}